use crate::{bihashmap, common::keyboard::KeyboardKey};
use bimap::BiHashMap;
use once_cell::sync::Lazy;

impl From<KeyboardKey> for u32 {
    fn from(key: KeyboardKey) -> Self {
        match key {
            KeyboardKey::Other(code) => code,
            _ => *SCANCODE_MAP.get_by_left(&key).unwrap(),
        }
    }
}

impl From<u32> for KeyboardKey {
    fn from(code: u32) -> Self {
        if let Some(key) = SCANCODE_MAP.get_by_right(&code) {
            *key
        } else {
            KeyboardKey::Other(code)
        }
    }
}

const SCANCODE_MAP: Lazy<BiHashMap<KeyboardKey, u32>> = Lazy::new(|| {
    bihashmap! {
        KeyboardKey::Backspace => 0x08,
        KeyboardKey::Tab => 0x09,
        KeyboardKey::Enter => 0x0D,
        KeyboardKey::Shift => 0x10,
        KeyboardKey::Ctrl => 0x11,
        KeyboardKey::Alt => 0x12,
        KeyboardKey::CapsLock => 0x14,
        KeyboardKey::Esc => 0x1B,
        KeyboardKey::Henkan => 0x1C,
        KeyboardKey::Muhenkan => 0x1D,
        KeyboardKey::Space => 0x20,
        KeyboardKey::PageUp => 0x21,
        KeyboardKey::PageDown => 0x22,
        KeyboardKey::End => 0x23,
        KeyboardKey::Home => 0x24,
        KeyboardKey::LeftArrow => 0x25,
        KeyboardKey::UpArrow => 0x26,
        KeyboardKey::RightArrow => 0x27,
        KeyboardKey::DownArrow => 0x28,
        KeyboardKey::PrintScreen => 0x2C,
        KeyboardKey::Insert => 0x2D,
        KeyboardKey::Delete => 0x2E,
        KeyboardKey::Key0 => 0x30,
        KeyboardKey::Key1 => 0x31,
        KeyboardKey::Key2 => 0x32,
        KeyboardKey::Key3 => 0x33,
        KeyboardKey::Key4 => 0x34,
        KeyboardKey::Key5 => 0x35,
        KeyboardKey::Key6 => 0x36,
        KeyboardKey::Key7 => 0x37,
        KeyboardKey::Key8 => 0x38,
        KeyboardKey::Key9 => 0x39,
        KeyboardKey::A => 0x41,
        KeyboardKey::B => 0x42,
        KeyboardKey::C => 0x43,
        KeyboardKey::D => 0x44,
        KeyboardKey::E => 0x45,
        KeyboardKey::F => 0x46,
        KeyboardKey::G => 0x47,
        KeyboardKey::H => 0x48,
        KeyboardKey::I => 0x49,
        KeyboardKey::J => 0x4A,
        KeyboardKey::K => 0x4B,
        KeyboardKey::L => 0x4C,
        KeyboardKey::M => 0x4D,
        KeyboardKey::N => 0x4E,
        KeyboardKey::O => 0x4F,
        KeyboardKey::P => 0x50,
        KeyboardKey::Q => 0x51,
        KeyboardKey::R => 0x52,
        KeyboardKey::S => 0x53,
        KeyboardKey::T => 0x54,
        KeyboardKey::U => 0x55,
        KeyboardKey::V => 0x56,
        KeyboardKey::W => 0x57,
        KeyboardKey::X => 0x58,
        KeyboardKey::Y => 0x59,
        KeyboardKey::Z => 0x5A,
        KeyboardKey::LMeta => 0x5B,
        KeyboardKey::RMeta => 0x5C,
        KeyboardKey::Application => 0x5D,
        KeyboardKey::Numpad0 => 0x60,
        KeyboardKey::Numpad1 => 0x61,
        KeyboardKey::Numpad2 => 0x62,
        KeyboardKey::Numpad3 => 0x63,
        KeyboardKey::Numpad4 => 0x64,
        KeyboardKey::Numpad5 => 0x65,
        KeyboardKey::Numpad6 => 0x66,
        KeyboardKey::Numpad7 => 0x67,
        KeyboardKey::Numpad8 => 0x68,
        KeyboardKey::Numpad9 => 0x69,
        KeyboardKey::NumpadAsterisk => 0x6A,
        KeyboardKey::NumpadPlus => 0x6B,
        KeyboardKey::NumpadMinus => 0x6D,
        KeyboardKey::NumpadDot => 0x6E,
        KeyboardKey::NumpadSlash => 0x6F,
        KeyboardKey::F1 => 0x70,
        KeyboardKey::F2 => 0x71,
        KeyboardKey::F3 => 0x72,
        KeyboardKey::F4 => 0x73,
        KeyboardKey::F5 => 0x74,
        KeyboardKey::F6 => 0x75,
        KeyboardKey::F7 => 0x76,
        KeyboardKey::F8 => 0x77,
        KeyboardKey::F9 => 0x78,
        KeyboardKey::F10 => 0x79,
        KeyboardKey::F11 => 0x7A,
        KeyboardKey::F12 => 0x7B,
        KeyboardKey::F13 => 0x7C,
        KeyboardKey::F14 => 0x7D,
        KeyboardKey::F15 => 0x7E,
        KeyboardKey::F16 => 0x7F,
        KeyboardKey::F17 => 0x80,
        KeyboardKey::F18 => 0x81,
        KeyboardKey::F19 => 0x82,
        KeyboardKey::F20 => 0x83,
        KeyboardKey::F21 => 0x84,
        KeyboardKey::F22 => 0x85,
        KeyboardKey::F23 => 0x86,
        KeyboardKey::F24 => 0x87,
        KeyboardKey::Numlock => 0x90,
        KeyboardKey::ScrollLock => 0x91,
        KeyboardKey::LShift => 0xA0,
        KeyboardKey::RShift => 0xA1,
        KeyboardKey::LCtrl => 0xA2,
        KeyboardKey::RCtrl => 0xA3,
        KeyboardKey::LAlt => 0xA4,
        KeyboardKey::RAlt => 0xA5,
        KeyboardKey::Colon => 0xBA,
        KeyboardKey::SemiColon => 0xBB,
        KeyboardKey::Comma => 0xBC,
        KeyboardKey::Minus => 0xBD,
        KeyboardKey::Dot => 0xBE,
        KeyboardKey::Slash => 0xBF,
        KeyboardKey::At => 0xC0,
        KeyboardKey::LeftSquareBracket => 0xDB,
        KeyboardKey::BackSlashWithVerticalBar => 0xDC,
        KeyboardKey::RightSquareBracket => 0xDD,
        KeyboardKey::Hat => 0xDE,
        KeyboardKey::BackSlashWithUnderLine => 0xE2,
        KeyboardKey::Eisuu => 0xF0,
        KeyboardKey::KatakanaHiragana => 0xF2,
        KeyboardKey::HannkakuZenkaku => 0xF3,
    }
});
