[package]
name = "hookmap"
version = "0.1.0"
authors = ["keke1008 <keke2222337@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hookmap-core = { "path" = "../hookmap-core" }
derive-new = "0.5.9"
