[package]
name = "hookmap"
version = "0.1.0"
authors = ["keke1008 <keke2222337@gmail.com>"]
edition = "2018"
description = "Register hotkeys and simulate keyboard and mosue input."
license = "MIT OR Apache-2.0"
repository = "https://github.com/keke1008/hookmap"
keywords = ["hotkey", "keyboard", "mouse"]
categories = ["api-bindings"]
readme = "README.md"

[dependencies]
hookmap-core = { "path" = "../hookmap-core" }
derive-new = "0.5.9"
once_cell = "1.8.0"

[features]
block-input-event = []
